version: "3"

services:
    db:
        image: tjommi/vote-sql
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: secret
        networks: 
            - my_network

    vote:
        image: tjommi/vote-app
        ports: 
            - "3000:80"
        deploy:
            replicas: 3
            restart_policy:
                condition: on-failure
        networks: 
            - my_network

    api:
        image: tjommi/vote-api
        ports:
            - "8080:8080"
        deploy:
            replicas: 3
            restart_policy: 
                condition: on-failure
        networks: 
            - my_network

networks:
    my_network:
        driver: overlay
